"""Add subscription renewal logs table

Revision ID: abb4a44378ca
Revises: d0d747478175
Create Date: 2025-05-25 21:07:06.917554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb4a44378ca'
down_revision = 'd0d747478175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_renewal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('previous_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('new_renewal_date', sa.DateTime(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('renewed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_renewal_logs')
    # ### end Alembic commands ###
